version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::730335384354:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-eTD2oqH3ZAMj"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::730335384354:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-HLMAHYBN8VHL"
cloudformation_execution_role = "arn:aws:iam::730335384354:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-K24NNGwQ26AG"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-8koj8hk955ka"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::730335384354:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-8FkCVqGSSO8l"
cloudformation_execution_role = "arn:aws:iam::730335384354:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-bvuTdvEccqog"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-um8ct7hesolz"
image_repository = ""
region = "us-east-1"
